CREATE SCHEMA proyectoIntegrador;
USE proyectoIntegrador;

CREATE TABLE usuarios(
id_usuario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
email VARCHAR(100),
usuario VARCHAR(50),
contrasenia VARCHAR(50),
fecha_nacimiento DATE NOT NULL,
numero_documento INT UNSIGNED NOT NULL, 
foto VARCHAR (1000) NOT NULL
/* createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP */
);


/* CREATE TABLE posteos(
id_post INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
id_usuario INT UNSIGNED FOREIGN KEY AUTO_INCREMENT,
name_img VARCHAR(100) NOT NULL,
descripcion VARCHAR (1000),
);*/

/* CREATE TABLE comentarios(
id_comentario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
id_post INT UNSIGNED FOREIGN KEY AUTO_INCREMENT,
id_usuario INT UNSIGNED FOREIGN KEY AUTO_INCREMENT,
comentario VARCHAR (1000) NOT NULL
);*/


/* DROP SCHEMA proyectoIntegrador */